[package]
name = "widecast-spsc"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
arc-swap = { version = "1.6" }
cfg-if = "1.0.0"

[target.'cfg(loom)'.dependencies]
loom = { version = "0.7", features = ["checkpoint"] }
tracing = "0.1.40"

