
format_macro_matchers = true
format_macro_bodies = true
wrap_comments = true

# rust-analyzer generally inserts use statements wherever so this standardizes
# their order and granularity.
imports_granularity = "Module"
group_imports = "StdExternalCrate"
