[package]
name = "masswake"
version = "0.1.0"
edition = "2021"

[dependencies]
arc-swap = "1.6.0"
crossbeam-utils = "0.8.16"
noop-waker = "0.1"
thread_local = "1.1.7"

[dev-dependencies]
tokio = { version = "1.0", features = ["rt"] }
